#QUE TRANSA CON LA PANZA
#added comments
import os, sys, r2pipe, json
import pymongo
from pymongo import MongoClient
from Script import Script
from Plugin import Plugin
from Project import Project
from PointOfInterest import POI
from BinaryFile import BinaryFile
from Metadata import Metadata
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets

#comment
class Ui_MainWindow(object):
    def __init__(self):
        self.windowNew = QtWidgets.QDialog()
        self.windowPlug = QtWidgets.QDialog()
        self.windowPOI = QtWidgets.QDialog()
        self.windowBinaryError = QtWidgets.QDialog()
        self.windowFileError = QtWidgets.QDialog()
        self.windowAnalysisResult = QtWidgets.QDialog()
        self.windowOutputField = QtWidgets.QDialog()
        self.windowComment = QtWidgets.QDialog()
        self.windowPluginError = QtWidgets.QDialog()
        self.text = None
        self.contents = None
        self.le = None
        self.path = ""

        cluster = MongoClient("mongodb://localhost:27017")
        db = cluster.test
        self.collection = db["test"]

    def projectWindow(self):
        self.setupUiCreateProject(self.windowNew)
        self.windowNew.show()

    def createProject(self, name, binary, description):
        if not name or not binary or not description:
            print("Failed")
        else:
            self.project = Project(name, binary, description)
            self.projectNameField.setText(self.project.name)
            self.binaryFilePathField.setText(self.project.binary)
            self.projectDescriptionField.setText(self.project.description)

            self.r2 = r2pipe.open(self.path)

            self.binaryInfo = self.r2.cmdj('ij')

            self.metadata = Metadata(self.binaryInfo.get("bin").get("arch"), self.binaryInfo.get("bin").get("os"),
                                     self.binaryInfo.get("bin").get("bintype"),
                                     self.binaryInfo.get("bin").get("machine"), self.binaryInfo.get("bin").get("class"),
                                     self.binaryInfo.get("bin").get("bits"),
                                     self.binaryInfo.get("bin").get("lang"), self.binaryInfo.get("bin").get("canary"),
                                     self.binaryInfo.get("bin").get("endian"),
                                     self.binaryInfo.get("bin").get("crypto"), self.binaryInfo.get("bin").get("nx"),
                                     self.binaryInfo.get("bin").get("pic"),
                                     self.binaryInfo.get("bin").get("relocs"),
                                     self.binaryInfo.get("bin").get("striped"), self.binaryInfo.get("core").get("type"))

            self.binary = BinaryFile(self.path, self.metadata)

            try:
                if (self.binary.metadata.arch != "x86") or (
                        self.binary.metadata.type != "Executable file" and self.binary.metadata.type != "EXEC (Executable file)"):
                    self.binaryErrorWindow()
                    self.r2 = ""
                    self.fileProperties.setText("")
                else:
                    self.binaryFilePathEdit.setText(str(self.path))
                    self.fileProperties.append("arch\t\t\t" + self.binary.metadata.arch + "\n")
                    self.fileProperties.append("os\t\t\t" + self.binary.metadata.os + "\n")
                    self.fileProperties.append("bintype\t\t\t" + self.binary.metadata.binaryType + "\n")
                    self.fileProperties.append("machine\t\t\t" + self.binary.metadata.machine + "\n")
                    self.fileProperties.append("class\t\t\t" + self.binary.metadata.classVariable + "\n")
                    self.fileProperties.append("bits\t\t\t" + str(self.binary.metadata.bits) + "\n")
                    self.fileProperties.append("language\t\t\t" + self.binary.metadata.language + "\n")
                    self.fileProperties.append("canary\t\t\t" + str(self.binary.metadata.canary) + "\n")
                    self.fileProperties.append("endian\t\t\t" + self.binary.metadata.endian + "\n")
                    self.fileProperties.append("crypto\t\t\t" + str(self.binary.metadata.crypto) + "\n")
                    self.fileProperties.append("nx\t\t\t" + str(self.binary.metadata.nx) + "\n")
                    self.fileProperties.append("pic\t\t\t" + str(self.binary.metadata.pic) + "\n")
                    self.fileProperties.append("relocs\t\t\t" + str(self.binary.metadata.relocs) + "\n")
                    self.fileProperties.append("stripped\t\t\t" + str(self.binary.metadata.stripped) + "\n")
                    self.fileProperties.append("extension\t\t\t" + self.binary.metadata.type + "\n")

                    self.binaryFilePathField.setText(self.path)

            except Exception as e:
                self.binaryErrorWindow()
                self.r2 = ""
                self.fileProperties.setText("")

    def getBinaryFilePath(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(self.binaryFilePathField, "Browse Binary File", "",
                                                            "Binary Files (*.exe *.out *.class *.docx)", options = options)
        if fileName:
            self.path = str(fileName)
            self.binaryFilePathEdit.setText(fileName)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1318, 755)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UI = QtWidgets.QTabWidget(self.centralwidget)
        self.UI.setGeometry(QtCore.QRect(0, 0, 1321, 721))
        self.UI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.UI.setElideMode(QtCore.Qt.ElideLeft)
        self.UI.setDocumentMode(True)
        self.UI.setTabsClosable(False)
        self.UI.setMovable(True)
        self.UI.setTabBarAutoHide(False)
        self.UI.setObjectName("UI")
        self.projectTab = QtWidgets.QWidget()
        self.projectTab.setObjectName("projectTab")
        self.projectViewGroup = QtWidgets.QGroupBox(self.projectTab)
        self.projectViewGroup.setGeometry(QtCore.QRect(20, 10, 261, 681))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.projectViewGroup.setFont(font)
        self.projectViewGroup.setObjectName("projectViewGroup")
        self.projectNewButton = QtWidgets.QPushButton(self.projectViewGroup)
        self.projectNewButton.setGeometry(QtCore.QRect(10, 640, 113, 32))
        self.projectNewButton.setObjectName("projectNewButton")
        self.projectList = QtWidgets.QListWidget(self.projectViewGroup)
        self.projectList.setGeometry(QtCore.QRect(10, 80, 231, 551))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.projectList.setFont(font)
        self.projectList.setObjectName("projectList")
        self.projectSearch = QtWidgets.QTextEdit(self.projectViewGroup)
        self.projectSearch.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.projectSearch.setObjectName("projectSearch")
        self.glass = QtWidgets.QLabel(self.projectViewGroup)
        self.glass.setGeometry(QtCore.QRect(190, 30, 51, 31))
        self.glass.setText("")
        self.glass.setPixmap(QtGui.QPixmap("../../cliparts-for-powerpoint-transparent-magnifying-glass-md.png"))
        self.glass.setScaledContents(True)
        self.glass.setObjectName("glass")
        self.projectSearchButton = QtWidgets.QPushButton(self.projectViewGroup)
        self.projectSearchButton.setGeometry(QtCore.QRect(180, 30, 61, 31))
        self.projectSearchButton.setObjectName("projectSearchButton")
        self.projectDeleteButton = QtWidgets.QPushButton(self.projectViewGroup)
        self.projectDeleteButton.setGeometry(QtCore.QRect(130, 640, 113, 32))
        self.projectDeleteButton.setObjectName("projectDeleteButton")
        self.detailedProjectView = QtWidgets.QGroupBox(self.projectTab)
        self.detailedProjectView.setGeometry(QtCore.QRect(310, 10, 991, 681))
        self.detailedProjectView.setTitle("")
        self.detailedProjectView.setObjectName("detailedProjectView")
        self.saveProjectButton = QtWidgets.QPushButton(self.detailedProjectView)
        self.saveProjectButton.setGeometry(QtCore.QRect(820, 640, 113, 32))
        self.saveProjectButton.setObjectName("saveProjectButton")
        self.projectNameLabel = QtWidgets.QLabel(self.detailedProjectView)
        self.projectNameLabel.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.projectDescriptionLabel = QtWidgets.QLabel(self.detailedProjectView)
        self.projectDescriptionLabel.setGeometry(QtCore.QRect(10, 60, 141, 16))
        self.projectDescriptionLabel.setObjectName("projectDescriptionLabel")
        self.binaryFilePathLabel = QtWidgets.QLabel(self.detailedProjectView)
        self.binaryFilePathLabel.setGeometry(QtCore.QRect(10, 180, 131, 16))
        self.binaryFilePathLabel.setObjectName("binaryFilePathLabel")
        self.binaryFilePropertiesLabel = QtWidgets.QLabel(self.detailedProjectView)
        self.binaryFilePropertiesLabel.setGeometry(QtCore.QRect(10, 230, 151, 16))
        self.binaryFilePropertiesLabel.setObjectName("binaryFilePropertiesLabel")
        self.projectNameField = QtWidgets.QLineEdit(self.detailedProjectView)
        self.projectNameField.setGeometry(QtCore.QRect(150, 30, 781, 21))
        self.projectNameField.setObjectName("projectNameField")
        self.projectDescriptionField = QtWidgets.QLineEdit(self.detailedProjectView)
        self.projectDescriptionField.setGeometry(QtCore.QRect(150, 60, 781, 111))
        self.projectDescriptionField.setObjectName("projectDescriptionField")
        self.binaryFilePathField = QtWidgets.QLineEdit(self.detailedProjectView)
        self.binaryFilePathField.setGeometry(QtCore.QRect(150, 180, 781, 21))
        self.binaryFilePathField.setObjectName("binaryFilePathField")
        self.binaryFilePropertiesField = QtWidgets.QScrollArea(self.detailedProjectView)
        self.binaryFilePropertiesField.setGeometry(QtCore.QRect(150, 230, 781, 401))
        self.binaryFilePropertiesField.setWidgetResizable(True)
        self.binaryFilePropertiesField.setObjectName("binaryFilePropertiesField")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.BEAT = QtWidgets.QColumnView(self.scrollAreaWidgetContents)
        self.BEAT.setGeometry(QtCore.QRect(0, 0, 671, 351))
        self.BEAT.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.BEAT.setTabKeyNavigation(True)
        self.BEAT.setDragEnabled(False)
        self.BEAT.setAlternatingRowColors(True)
        self.BEAT.setObjectName("BEAT")
        self.fileProperties = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.fileProperties.setGeometry(QtCore.QRect(0, 0, 781, 401))
        self.fileProperties.setObjectName("fileProperties")
        self.filePropertiesLine = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.filePropertiesLine.setGeometry(QtCore.QRect(220, 0, 16, 581))
        self.filePropertiesLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.filePropertiesLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.filePropertiesLine.setObjectName("filePropertiesLine")
        self.binaryFilePropertiesField.setWidget(self.scrollAreaWidgetContents)
        self.detailedProjectViewLabel = QtWidgets.QLabel(self.detailedProjectView)
        self.detailedProjectViewLabel.setGeometry(QtCore.QRect(10, 0, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detailedProjectViewLabel.setFont(font)
        self.detailedProjectViewLabel.setObjectName("detailedProjectViewLabel")
        self.UI.addTab(self.projectTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.analysisSection = QtWidgets.QGroupBox(self.analysisTab)
        self.analysisSection.setGeometry(QtCore.QRect(310, 20, 991, 671))
        self.analysisSection.setTitle("")
        self.analysisSection.setObjectName("analysisSection")
        self.detailedAnalysisViewLabel = QtWidgets.QLabel(self.analysisSection)
        self.detailedAnalysisViewLabel.setGeometry(QtCore.QRect(40, 80, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detailedAnalysisViewLabel.setFont(font)
        self.detailedAnalysisViewLabel.setObjectName("detailedAnalysisViewLabel")
        self.terminalLabel = QtWidgets.QLabel(self.analysisSection)
        self.terminalLabel.setGeometry(QtCore.QRect(40, 480, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.terminalLabel.setFont(font)
        self.terminalLabel.setObjectName("terminalLabel")
        self.outputFieldViewButton = QtWidgets.QPushButton(self.analysisSection)
        self.outputFieldViewButton.setGeometry(QtCore.QRect(780, 420, 151, 30))
        self.outputFieldViewButton.setObjectName("outputFieldViewButton")
        self.terminalField = QtWidgets.QTextEdit(self.analysisSection)
        self.terminalField.setGeometry(QtCore.QRect(30, 510, 921, 121))
        self.terminalField.setObjectName("terminalField")
        self.frame = QtWidgets.QFrame(self.analysisSection)
        self.frame.setGeometry(QtCore.QRect(30, 110, 921, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.runList = QtWidgets.QListWidget(self.frame)
        self.runList.setGeometry(QtCore.QRect(20, 20, 161, 281))
        self.runList.setObjectName("runList")
        self.detailedPoiAnalysisField = QtWidgets.QTextBrowser(self.frame)
        self.detailedPoiAnalysisField.setGeometry(QtCore.QRect(200, 20, 701, 281))
        self.detailedPoiAnalysisField.setObjectName("detailedPoiAnalysisField")
        self.deleteAnalysisResultButton = QtWidgets.QPushButton(self.frame)
        self.deleteAnalysisResultButton.setGeometry(QtCore.QRect(20, 310, 171, 30))
        self.deleteAnalysisResultButton.setObjectName("deleteAnalysisResultButton")
        self.pluginLabel = QtWidgets.QLabel(self.analysisTab)
        self.pluginLabel.setGeometry(QtCore.QRect(360, 30, 61, 31))
        self.pluginLabel.setObjectName("pluginLabel")
        self.staticAnalysisLabel = QtWidgets.QLabel(self.analysisTab)
        self.staticAnalysisLabel.setGeometry(QtCore.QRect(880, 40, 101, 21))
        self.staticAnalysisLabel.setObjectName("staticAnalysisLabel")
        self.poiTypeLabel = QtWidgets.QLabel(self.analysisTab)
        self.poiTypeLabel.setGeometry(QtCore.QRect(360, 70, 61, 21))
        self.poiTypeLabel.setObjectName("poiTypeLabel")
        self.dynamicAnalysisLabel = QtWidgets.QLabel(self.analysisTab)
        self.dynamicAnalysisLabel.setGeometry(QtCore.QRect(880, 80, 121, 21))
        self.dynamicAnalysisLabel.setObjectName("dynamicAnalysisLabel")
        self.pluginDropDownAnalysis = QtWidgets.QComboBox(self.analysisTab)
        self.pluginDropDownAnalysis.setGeometry(QtCore.QRect(430, 30, 131, 32))
        self.pluginDropDownAnalysis.setObjectName("pluginDropDownAnalysis")
        self.pluginDropDownAnalysis.addItem("")
        self.runStaticButton = QtWidgets.QPushButton(self.analysisTab)
        self.runStaticButton.setGeometry(QtCore.QRect(1010, 40, 111, 32))
        self.runStaticButton.setObjectName("runStaticButton")
        self.poiTypeDropDownAnalysis = QtWidgets.QComboBox(self.analysisTab)
        self.poiTypeDropDownAnalysis.setGeometry(QtCore.QRect(430, 70, 131, 32))
        self.poiTypeDropDownAnalysis.setEditable(False)
        self.poiTypeDropDownAnalysis.setObjectName("poiTypeDropDownAnalysis")
        self.poiTypeDropDownAnalysis.addItem("")
        self.runDynamicButton = QtWidgets.QPushButton(self.analysisTab)
        self.runDynamicButton.setGeometry(QtCore.QRect(1010, 70, 113, 32))
        self.runDynamicButton.setObjectName("runDynamicButton")
        self.stopDynamicButton = QtWidgets.QPushButton(self.analysisTab)
        self.stopDynamicButton.setGeometry(QtCore.QRect(1130, 70, 113, 32))
        self.stopDynamicButton.setObjectName("stopDynamicButton")
        self.analysisView = QtWidgets.QGroupBox(self.analysisTab)
        self.analysisView.setGeometry(QtCore.QRect(20, 10, 261, 681))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.analysisView.setFont(font)
        self.analysisView.setObjectName("analysisView")
        self.poiAnalysisList = QtWidgets.QListWidget(self.analysisView)
        self.poiAnalysisList.setGeometry(QtCore.QRect(10, 30, 231, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.poiAnalysisList.setFont(font)
        self.poiAnalysisList.setObjectName("poiAnalysisList")
        self.commentViewButton = QtWidgets.QPushButton(self.analysisView)
        self.commentViewButton.setGeometry(QtCore.QRect(100, 640, 141, 30))
        self.commentViewButton.setObjectName("commentViewButton")
        self.UI.addTab(self.analysisTab, "")
        self.pluginManagementTab = QtWidgets.QWidget()
        self.pluginManagementTab.setObjectName("pluginManagementTab")
        self.pluginView = QtWidgets.QGroupBox(self.pluginManagementTab)
        self.pluginView.setGeometry(QtCore.QRect(20, 10, 261, 681))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pluginView.setFont(font)
        self.pluginView.setObjectName("pluginView")
        self.newPluginButton = QtWidgets.QPushButton(self.pluginView)
        self.newPluginButton.setGeometry(QtCore.QRect(10, 640, 113, 32))
        self.newPluginButton.setObjectName("newPluginButton")
        self.pluginSearch = QtWidgets.QTextEdit(self.pluginView)
        self.pluginSearch.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.pluginSearch.setObjectName("pluginSearch")
        self.pluginManagementList = QtWidgets.QListWidget(self.pluginView)
        self.pluginManagementList.setGeometry(QtCore.QRect(10, 80, 231, 551))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pluginManagementList.setFont(font)
        self.pluginManagementList.setObjectName("pluginManagementList")
        self.glass_2 = QtWidgets.QLabel(self.pluginView)
        self.glass_2.setGeometry(QtCore.QRect(190, 30, 51, 31))
        self.glass_2.setText("")
        self.glass_2.setPixmap(QtGui.QPixmap("../../cliparts-for-powerpoint-transparent-magnifying-glass-md.png"))
        self.glass_2.setScaledContents(True)
        self.glass_2.setObjectName("glass_2")
        self.searchPluginButton = QtWidgets.QPushButton(self.pluginView)
        self.searchPluginButton.setGeometry(QtCore.QRect(180, 30, 61, 31))
        self.searchPluginButton.setObjectName("searchPluginButton")
        self.deletePluginButton = QtWidgets.QPushButton(self.pluginView)
        self.deletePluginButton.setGeometry(QtCore.QRect(130, 640, 113, 32))
        self.deletePluginButton.setObjectName("deletePluginButton")
        self.detailedPluginView = QtWidgets.QGroupBox(self.pluginManagementTab)
        self.detailedPluginView.setGeometry(QtCore.QRect(310, 10, 991, 681))
        self.detailedPluginView.setTitle("")
        self.detailedPluginView.setObjectName("detailedPluginView")
        self.pluginStructureLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.pluginStructureLabel.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.pluginStructureLabel.setObjectName("pluginStructureLabel")
        self.pluginPredefinedLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.pluginPredefinedLabel.setGeometry(QtCore.QRect(10, 60, 191, 16))
        self.pluginPredefinedLabel.setObjectName("pluginPredefinedLabel")
        self.pluginNameLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.pluginNameLabel.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.pluginNameLabel.setObjectName("pluginNameLabel")
        self.pluginDescriptionLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.pluginDescriptionLabel.setGeometry(QtCore.QRect(10, 120, 141, 16))
        self.pluginDescriptionLabel.setObjectName("pluginDescriptionLabel")
        self.defaultOutputFieldLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.defaultOutputFieldLabel.setGeometry(QtCore.QRect(10, 220, 161, 16))
        self.defaultOutputFieldLabel.setObjectName("defaultOutputFieldLabel")
        self.poiLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.poiLabel.setGeometry(QtCore.QRect(10, 250, 111, 16))
        self.poiLabel.setObjectName("poiLabel")
        self.outputFieldDropDown = QtWidgets.QComboBox(self.detailedPluginView)
        self.outputFieldDropDown.setGeometry(QtCore.QRect(200, 210, 121, 32))
        self.outputFieldDropDown.setObjectName("outputFieldDropDown")
        self.outputFieldDropDown.addItem("")
        self.savePluginButton = QtWidgets.QPushButton(self.detailedPluginView)
        self.savePluginButton.setGeometry(QtCore.QRect(820, 640, 113, 32))
        self.savePluginButton.setObjectName("savePluginButton")
        self.detailedPluginViewLabel = QtWidgets.QLabel(self.detailedPluginView)
        self.detailedPluginViewLabel.setGeometry(QtCore.QRect(10, 0, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detailedPluginViewLabel.setFont(font)
        self.detailedPluginViewLabel.setObjectName("detailedPluginViewLabel")
        self.XMLEditorButton = QtWidgets.QPushButton(self.detailedPluginView)
        self.XMLEditorButton.setGeometry(QtCore.QRect(20, 280, 113, 32))
        self.XMLEditorButton.setObjectName("XMLEditorButton")
        self.pluginStructureField = QtWidgets.QLineEdit(self.detailedPluginView)
        self.pluginStructureField.setGeometry(QtCore.QRect(200, 30, 731, 21))
        self.pluginStructureField.setObjectName("pluginStructureField")
        self.pluginPredefinedField = QtWidgets.QLineEdit(self.detailedPluginView)
        self.pluginPredefinedField.setGeometry(QtCore.QRect(200, 60, 731, 21))
        self.pluginPredefinedField.setObjectName("pluginPredefinedField")
        self.pluginNameField = QtWidgets.QLineEdit(self.detailedPluginView)
        self.pluginNameField.setGeometry(QtCore.QRect(200, 90, 731, 21))
        self.pluginNameField.setObjectName("pluginNameField")
        self.pluginDescriptionField = QtWidgets.QTextEdit(self.detailedPluginView)
        self.pluginDescriptionField.setGeometry(QtCore.QRect(200, 120, 731, 74))
        self.pluginDescriptionField.setObjectName("pluginDescriptionField")
        self.poiPluginField = QtWidgets.QTextEdit(self.detailedPluginView)
        self.poiPluginField.setGeometry(QtCore.QRect(200, 250, 731, 381))
        self.poiPluginField.setObjectName("poiPluginField")
        self.UI.addTab(self.pluginManagementTab, "")
        self.poiTab = QtWidgets.QWidget()
        self.poiTab.setObjectName("poiTab")
        self.poiView = QtWidgets.QGroupBox(self.poiTab)
        self.poiView.setGeometry(QtCore.QRect(20, 10, 261, 681))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.poiView.setFont(font)
        self.poiView.setObjectName("poiView")
        self.newPOIButton = QtWidgets.QPushButton(self.poiView)
        self.newPOIButton.setGeometry(QtCore.QRect(10, 640, 113, 32))
        self.newPOIButton.setObjectName("newPOIButton")
        self.poiSearch = QtWidgets.QTextEdit(self.poiView)
        self.poiSearch.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.poiSearch.setObjectName("poiSearch")
        self.poiList = QtWidgets.QListWidget(self.poiView)
        self.poiList.setGeometry(QtCore.QRect(10, 80, 231, 551))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.poiList.setFont(font)
        self.poiList.setObjectName("poiList")
        self.glass_3 = QtWidgets.QLabel(self.poiView)
        self.glass_3.setGeometry(QtCore.QRect(190, 30, 51, 31))
        self.glass_3.setText("")
        self.glass_3.setPixmap(QtGui.QPixmap("../../cliparts-for-powerpoint-transparent-magnifying-glass-md.png"))
        self.glass_3.setScaledContents(True)
        self.glass_3.setObjectName("glass_3")
        self.poiSearchButton = QtWidgets.QPushButton(self.poiView)
        self.poiSearchButton.setGeometry(QtCore.QRect(180, 30, 61, 31))
        self.poiSearchButton.setObjectName("poiSearchButton")
        self.poiDeleteButton = QtWidgets.QPushButton(self.poiView)
        self.poiDeleteButton.setGeometry(QtCore.QRect(130, 640, 113, 32))
        self.poiDeleteButton.setObjectName("poiDeleteButton")
        self.poiDetailedView = QtWidgets.QGroupBox(self.poiTab)
        self.poiDetailedView.setGeometry(QtCore.QRect(310, 10, 991, 681))
        self.poiDetailedView.setTitle("")
        self.poiDetailedView.setObjectName("poiDetailedView")
        self.pluginPoiLabel = QtWidgets.QLabel(self.poiDetailedView)
        self.pluginPoiLabel.setGeometry(QtCore.QRect(40, 20, 51, 16))
        self.pluginPoiLabel.setObjectName("pluginPoiLabel")
        self.poiFilterLabel = QtWidgets.QLabel(self.poiDetailedView)
        self.poiFilterLabel.setGeometry(QtCore.QRect(40, 70, 71, 16))
        self.poiFilterLabel.setObjectName("poiFilterLabel")
        self.poiSaveButton = QtWidgets.QPushButton(self.poiDetailedView)
        self.poiSaveButton.setGeometry(QtCore.QRect(820, 620, 113, 32))
        self.poiSaveButton.setObjectName("poiSaveButton")
        self.poiPluginDropDown = QtWidgets.QComboBox(self.poiDetailedView)
        self.poiPluginDropDown.setGeometry(QtCore.QRect(110, 10, 131, 32))
        self.poiPluginDropDown.setObjectName("poiPluginDropDown")
        self.poiPluginDropDown.addItem("")
        self.poiFilterDropDown = QtWidgets.QComboBox(self.poiDetailedView)
        self.poiFilterDropDown.setGeometry(QtCore.QRect(110, 60, 131, 32))
        self.poiFilterDropDown.setEditable(False)
        self.poiFilterDropDown.setObjectName("poiFilterDropDown")
        self.poiFilterDropDown.addItem("")
        self.detailedPoiViewLabel = QtWidgets.QLabel(self.poiDetailedView)
        self.detailedPoiViewLabel.setGeometry(QtCore.QRect(40, 120, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detailedPoiViewLabel.setFont(font)
        self.detailedPoiViewLabel.setObjectName("detailedPoiViewLabel")
        self.poiViewField = QtWidgets.QTextBrowser(self.poiDetailedView)
        self.poiViewField.setGeometry(QtCore.QRect(30, 140, 891, 461))
        self.poiViewField.setObjectName("poiViewField")
        self.UI.addTab(self.poiTab, "")
        self.Documentation = QtWidgets.QWidget()
        self.Documentation.setObjectName("Documentation")
        self.detailedDocumentView = QtWidgets.QGroupBox(self.Documentation)
        self.detailedDocumentView.setGeometry(QtCore.QRect(310, 10, 991, 681))
        self.detailedDocumentView.setTitle("")
        self.detailedDocumentView.setObjectName("detailedDocumentView")
        self.documentViewField = QtWidgets.QTextEdit(self.detailedDocumentView)
        self.documentViewField.setGeometry(QtCore.QRect(20, 30, 911, 631))
        self.documentViewField.setObjectName("documentViewField")
        self.detailedDocumentationViewLabel = QtWidgets.QLabel(self.detailedDocumentView)
        self.detailedDocumentationViewLabel.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detailedDocumentationViewLabel.setFont(font)
        self.detailedDocumentationViewLabel.setObjectName("detailedDocumentationViewLabel")
        self.documentView = QtWidgets.QGroupBox(self.Documentation)
        self.documentView.setGeometry(QtCore.QRect(20, 10, 261, 681))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.documentView.setFont(font)
        self.documentView.setObjectName("documentView")
        self.documentSearch = QtWidgets.QTextEdit(self.documentView)
        self.documentSearch.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.documentSearch.setObjectName("documentSearch")
        self.documentList = QtWidgets.QListWidget(self.documentView)
        self.documentList.setGeometry(QtCore.QRect(10, 80, 231, 581))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.documentList.setFont(font)
        self.documentList.setObjectName("documentList")
        self.searchDocumentButton = QtWidgets.QPushButton(self.documentView)
        self.searchDocumentButton.setGeometry(QtCore.QRect(180, 30, 61, 31))
        self.searchDocumentButton.setObjectName("searchDocumentButton")
        self.UI.addTab(self.Documentation, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.newPluginButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newPOIButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outputFieldViewButton.setFocusPolicy(QtCore.Qt.NoFocus)

        self.retranslateUi(MainWindow)
        self.UI.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.projectNewButton.clicked.connect(self.projectWindow)

    def setupUiCreateProject(self, NewProject):
        NewProject.setObjectName("NewProject")
        NewProject.resize(539, 333)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewProject)
        self.buttonBox.setGeometry(QtCore.QRect(110, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.projectNameLabel = QtWidgets.QLabel(NewProject)
        self.projectNameLabel.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.projectNameEdit = QtWidgets.QTextEdit(NewProject)
        self.projectNameEdit.setGeometry(QtCore.QRect(20, 30, 431, 21))
        self.projectNameEdit.setObjectName("projectNameEdit")
        self.projectDescriptionLabel = QtWidgets.QLabel(NewProject)
        self.projectDescriptionLabel.setGeometry(QtCore.QRect(20, 110, 131, 16))
        self.projectDescriptionLabel.setObjectName("projectDescriptionLabel")
        self.projectDescriptionEdit = QtWidgets.QTextEdit(NewProject)
        self.projectDescriptionEdit.setGeometry(QtCore.QRect(20, 140, 431, 141))
        self.projectDescriptionEdit.setObjectName("projectDescriptionEdit")
        self.binaryFilePathEdit = QtWidgets.QTextEdit(NewProject)
        self.binaryFilePathEdit.setGeometry(QtCore.QRect(20, 80, 431, 21))
        self.binaryFilePathEdit.setObjectName("binaryFilePathEdit")
        self.binaryFilePathLabel = QtWidgets.QLabel(NewProject)
        self.binaryFilePathLabel.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.binaryFilePathLabel.setObjectName("binaryFilePathLabel")
        self.binaryFilePathBrowse = QtWidgets.QPushButton(NewProject)
        self.binaryFilePathBrowse.setGeometry(QtCore.QRect(454, 80, 81, 31))
        self.binaryFilePathBrowse.setObjectName("binaryFilePathBrowse")

        self.retranslateUiCreateProject(NewProject)
        self.buttonBox.accepted.connect(NewProject.accept)
        self.buttonBox.rejected.connect(NewProject.reject)
        QtCore.QMetaObject.connectSlotsByName(NewProject)

        self.binaryFilePathEdit.setEnabled(False)

        self.binaryFilePathBrowse.clicked.connect(self.getBinaryFilePath)

        self.buttonBox.accepted.connect(
            lambda: self.createProject(self.projectNameEdit.toPlainText(), self.binaryFilePathEdit.toPlainText(),
                                       self.projectDescriptionEdit.toPlainText())
        )

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BEAT: Binary Extraction and Analysis Tool"))
        self.projectViewGroup.setTitle(_translate("MainWindow", "Project View"))
        self.projectNewButton.setText(_translate("MainWindow", "New"))
        self.projectSearch.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"><br /></p></body></html>"))
        self.projectSearchButton.setText(_translate("MainWindow", "🔍 "))
        self.projectDeleteButton.setText(_translate("MainWindow", "- Delete"))
        self.saveProjectButton.setText(_translate("MainWindow", "+ Save"))
        self.projectNameLabel.setText(_translate("MainWindow", "Project Name"))
        self.projectDescriptionLabel.setText(_translate("MainWindow", "Project Description"))
        self.binaryFilePathLabel.setText(_translate("MainWindow", "Binary File Path"))
        self.binaryFilePropertiesLabel.setText(_translate("MainWindow", "Binary File Properties"))
        self.detailedProjectViewLabel.setText(_translate("MainWindow", "Detailed Project View"))
        self.UI.setTabText(self.UI.indexOf(self.projectTab), _translate("MainWindow", "Project"))
        self.detailedAnalysisViewLabel.setText(_translate("MainWindow", "Detailed Analysis View"))
        self.terminalLabel.setText(_translate("MainWindow", "Terminal"))
        self.outputFieldViewButton.setText(_translate("MainWindow", "Output Field View"))
        self.deleteAnalysisResultButton.setText(_translate("MainWindow", "Delete Analysis Result"))
        self.pluginLabel.setText(_translate("MainWindow", "Plugin"))
        self.staticAnalysisLabel.setText(_translate("MainWindow", "Static Analysis"))
        self.poiTypeLabel.setText(_translate("MainWindow", "POI Type"))
        self.dynamicAnalysisLabel.setText(_translate("MainWindow", "Dynamic Analysis"))
        self.pluginDropDownAnalysis.setItemText(0, _translate("MainWindow", "Select"))
        self.runStaticButton.setText(_translate("MainWindow", "Run"))
        self.poiTypeDropDownAnalysis.setItemText(0, _translate("MainWindow", "Select"))
        self.runDynamicButton.setText(_translate("MainWindow", "Run"))
        self.stopDynamicButton.setText(_translate("MainWindow", "Stop"))
        self.analysisView.setTitle(_translate("MainWindow", "Analysis View"))
        self.commentViewButton.setText(_translate("MainWindow", "Comment View"))
        self.UI.setTabText(self.UI.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))
        self.pluginView.setTitle(_translate("MainWindow", "Plugin View"))
        self.newPluginButton.setText(_translate("MainWindow", "New"))
        self.pluginSearch.setHtml(_translate("MainWindow",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                             "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.searchPluginButton.setText(_translate("MainWindow", "🔍 "))
        self.deletePluginButton.setText(_translate("MainWindow", "- Delete"))
        self.pluginStructureLabel.setText(_translate("MainWindow", "Plugin Structure"))
        self.pluginPredefinedLabel.setText(_translate("MainWindow", "Plugin Predefined Data Set"))
        self.pluginNameLabel.setText(_translate("MainWindow", "Plugin Name"))
        self.pluginDescriptionLabel.setText(_translate("MainWindow", "Plugin Description"))
        self.defaultOutputFieldLabel.setText(_translate("MainWindow", "Default Output Field"))
        self.poiLabel.setText(_translate("MainWindow", "Points of Interest"))
        self.outputFieldDropDown.setItemText(0, _translate("MainWindow", "Output Field"))
        self.savePluginButton.setText(_translate("MainWindow", "+ Save"))
        self.detailedPluginViewLabel.setText(_translate("MainWindow", "Detailed Plugin View"))
        self.XMLEditorButton.setText(_translate("MainWindow", "XML Editor"))
        self.UI.setTabText(self.UI.indexOf(self.pluginManagementTab), _translate("MainWindow", "Plugin Management"))
        self.poiView.setTitle(_translate("MainWindow", "Point of Interest View"))
        self.newPOIButton.setText(_translate("MainWindow", "New"))
        self.poiSearch.setHtml(_translate("MainWindow",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.poiSearchButton.setText(_translate("MainWindow", "🔍 "))
        self.poiDeleteButton.setText(_translate("MainWindow", "- Delete"))
        self.pluginPoiLabel.setText(_translate("MainWindow", "Plugin"))
        self.poiFilterLabel.setText(_translate("MainWindow", "POI Filter"))
        self.poiSaveButton.setText(_translate("MainWindow", "+ Save"))
        self.poiPluginDropDown.setItemText(0, _translate("MainWindow", "Select"))
        self.poiFilterDropDown.setItemText(0, _translate("MainWindow", "Select"))
        self.detailedPoiViewLabel.setText(_translate("MainWindow", "Detailed Points of Interest View"))
        self.UI.setTabText(self.UI.indexOf(self.poiTab), _translate("MainWindow", "Points of Interest"))
        self.documentViewField.setHtml(_translate("MainWindow",
                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.detailedDocumentationViewLabel.setText(_translate("MainWindow", "Detailed Documentation View"))
        self.documentView.setTitle(_translate("MainWindow", "Documentation View"))
        self.documentSearch.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.searchDocumentButton.setText(_translate("MainWindow", "🔍 "))
        self.UI.setTabText(self.UI.indexOf(self.Documentation), _translate("MainWindow", "Documentation"))

    def retranslateUiCreateProject(self, NewProject):
        _translate = QtCore.QCoreApplication.translate
        NewProject.setWindowTitle(_translate("NewProject", "New Project"))
        self.projectNameLabel.setText(_translate("NewProject", "Project Name"))
        self.projectDescriptionLabel.setText(_translate("NewProject", "Project Description"))
        self.binaryFilePathLabel.setText(_translate("NewProject", "Binary File Path"))
        self.binaryFilePathBrowse.setText(_translate("NewProject", "Browse"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


# #
# #
#