import os, sys, r2pipe

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog

from Project import Project
from BinaryFile import BinaryFile
from Metadata import Metadata

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog

from pathlib import Path, PureWindowsPath

class AnalysisTab(object):

    #def __init__(self):

    def setupAnalysisTab(self, tab):

        self.tab = tab
        self.AnalysisViewContainer = QtWidgets.QGroupBox(self.tab)
        self.AnalysisViewContainer.setGeometry(QtCore.QRect(0, 0, 231, 621))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.AnalysisViewContainer.setFont(font)
        self.AnalysisViewContainer.setObjectName("AnalysisViewContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AnalysisViewContainer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.poilabel = QtWidgets.QLabel(self.AnalysisViewContainer)
        self.poilabel.setObjectName("poilabel")
        self.verticalLayout_6.addWidget(self.poilabel)
        self.poiAnalysisList = QtWidgets.QListWidget(self.AnalysisViewContainer)
        self.poiAnalysisList.setObjectName("poiAnalysisList")
        self.verticalLayout_6.addWidget(self.poiAnalysisList)
        self.CommentViewLayout = QtWidgets.QHBoxLayout()
        self.CommentViewLayout.setObjectName("CommentViewLayout")
        self.commentViewButton = QtWidgets.QPushButton(self.AnalysisViewContainer)
        self.commentViewButton.setObjectName("commentViewButton")
        self.CommentViewLayout.addWidget(self.commentViewButton)
        self.verticalLayout_6.addLayout(self.CommentViewLayout)
        self.DetailedAnalysisContainer = QtWidgets.QGroupBox(self.tab)
        self.DetailedAnalysisContainer.setGeometry(QtCore.QRect(240, 20, 981, 601))
        self.DetailedAnalysisContainer.setTitle("")
        self.DetailedAnalysisContainer.setObjectName("DetailedAnalysisContainer")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.DetailedAnalysisContainer)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(20, 10, 941, 38))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.PluginAnalysisLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.PluginAnalysisLayout.setContentsMargins(0, 0, 0, 0)
        self.PluginAnalysisLayout.setObjectName("PluginAnalysisLayout")
        self.PluginAnalysisLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.PluginAnalysisLabel.setObjectName("PluginAnalysisLabel")
        self.PluginAnalysisLayout.addWidget(self.PluginAnalysisLabel)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.PluginAnalysisLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.PluginAnalysisLayout.addItem(spacerItem6)
        self.pluginDropDownAnalysis = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        self.pluginDropDownAnalysis.setObjectName("pluginDropDownAnalysis")
        self.pluginDropDownAnalysis.addItem("")
        self.PluginAnalysisLayout.addWidget(self.pluginDropDownAnalysis)
        spacerItem7 = QtWidgets.QSpacerItem(640, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.PluginAnalysisLayout.addItem(spacerItem7)
        self.staticanalysislayout = QtWidgets.QHBoxLayout()
        self.staticanalysislayout.setObjectName("staticanalysislayout")
        self.staticLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.staticLabel.setObjectName("staticLabel")
        self.staticanalysislayout.addWidget(self.staticLabel)
        self.runStaticButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.runStaticButton.setObjectName("runStaticButton")
        self.staticanalysislayout.addWidget(self.runStaticButton)
        spacerItem8 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.staticanalysislayout.addItem(spacerItem8)
        self.PluginAnalysisLayout.addLayout(self.staticanalysislayout)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.DetailedAnalysisContainer)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(20, 50, 941, 38))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.PoiAnalysisLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.PoiAnalysisLayout.setContentsMargins(0, 0, 0, 0)
        self.PoiAnalysisLayout.setObjectName("PoiAnalysisLayout")
        self.POITypeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.POITypeLabel.setObjectName("POITypeLabel")
        self.PoiAnalysisLayout.addWidget(self.POITypeLabel)
        self.poiTypeDropDownAnalysis = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.poiTypeDropDownAnalysis.setObjectName("poiTypeDropDownAnalysis")
        self.poiTypeDropDownAnalysis.addItem("")
        self.PoiAnalysisLayout.addWidget(self.poiTypeDropDownAnalysis)
        spacerItem9 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.PoiAnalysisLayout.addItem(spacerItem9)
        self.dynamicLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.dynamicLabel.setObjectName("dynamicLabel")
        self.PoiAnalysisLayout.addWidget(self.dynamicLabel)
        self.runDynamicButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.runDynamicButton.setObjectName("runDynamicButton")
        self.PoiAnalysisLayout.addWidget(self.runDynamicButton)
        self.stopDynamicButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.stopDynamicButton.setObjectName("stopDynamicButton")
        self.PoiAnalysisLayout.addWidget(self.stopDynamicButton)
        self.DetailedAnalysisViewContainer = QtWidgets.QGroupBox(self.DetailedAnalysisContainer)
        self.DetailedAnalysisViewContainer.setGeometry(QtCore.QRect(10, 90, 951, 361))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DetailedAnalysisViewContainer.setFont(font)
        self.DetailedAnalysisViewContainer.setObjectName("DetailedAnalysisViewContainer")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.DetailedAnalysisViewContainer)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(9, 29, 191, 321))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.AnalysisListLayour = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.AnalysisListLayour.setContentsMargins(0, 0, 0, 0)
        self.AnalysisListLayour.setObjectName("AnalysisListLayour")
        self.runList = QtWidgets.QListWidget(self.verticalLayoutWidget_5)
        self.runList.setObjectName("runList")
        self.AnalysisListLayour.addWidget(self.runList)
        self.DeleteLayout = QtWidgets.QHBoxLayout()
        self.DeleteLayout.setObjectName("DeleteLayout")
        self.deleteAnalysisResultButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.deleteAnalysisResultButton.setObjectName("deleteAnalysisResultButton")
        self.DeleteLayout.addWidget(self.deleteAnalysisResultButton)
        self.AnalysisListLayour.addLayout(self.DeleteLayout)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.DetailedAnalysisViewContainer)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(220, 30, 721, 321))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.DetailedAnalysisLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.DetailedAnalysisLayout.setContentsMargins(0, 0, 0, 0)
        self.DetailedAnalysisLayout.setObjectName("DetailedAnalysisLayout")
        self.detailedPoiAnalysisField = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.detailedPoiAnalysisField.setFont(font)
        self.detailedPoiAnalysisField.setObjectName("detailedPoiAnalysisField")
        self.DetailedAnalysisLayout.addWidget(self.detailedPoiAnalysisField)
        self.OutputFieldButtonLayout = QtWidgets.QHBoxLayout()
        self.OutputFieldButtonLayout.setObjectName("OutputFieldButtonLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OutputFieldButtonLayout.addItem(spacerItem10)
        self.outputFieldViewButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.outputFieldViewButton.setObjectName("outputFieldViewButton")
        self.OutputFieldButtonLayout.addWidget(self.outputFieldViewButton)
        self.DetailedAnalysisLayout.addLayout(self.OutputFieldButtonLayout)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.DetailedAnalysisContainer)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 460, 941, 121))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.TerminalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.TerminalLayout.setContentsMargins(0, 0, 0, 0)
        self.TerminalLayout.setObjectName("TerminalLayout")
        self.terminalLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.terminalLabel.setFont(font)
        self.terminalLabel.setObjectName("terminalLabel")
        self.TerminalLayout.addWidget(self.terminalLabel)
        self.terminalField = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.terminalField.setObjectName("terminalField")
        self.TerminalLayout.addWidget(self.terminalField)

        return self.tab

    def retranslateAnalysisTab(self):

        _translate = QtCore.QCoreApplication.translate
        self.AnalysisViewContainer.setTitle(_translate("MainWindow", "Analysis View"))
        self.poilabel.setText(_translate("MainWindow", "Points of Interest"))
        self.commentViewButton.setText(_translate("MainWindow", "Comment View"))
        self.PluginAnalysisLabel.setText(_translate("MainWindow", "Plugin"))
        self.pluginDropDownAnalysis.setItemText(0, _translate("MainWindow", "Select"))
        self.staticLabel.setText(_translate("MainWindow", "Static Analysis"))
        self.runStaticButton.setText(_translate("MainWindow", "  Run  "))
        self.POITypeLabel.setText(_translate("MainWindow", "POI Type"))
        self.poiTypeDropDownAnalysis.setItemText(0, _translate("MainWindow", "Select"))
        self.dynamicLabel.setText(_translate("MainWindow", "Dynamic Analysis"))
        self.runDynamicButton.setText(_translate("MainWindow", "Run"))
        self.stopDynamicButton.setText(_translate("MainWindow", "Stop"))
        self.DetailedAnalysisViewContainer.setTitle(_translate("MainWindow", "Detailed Analysis View"))
        self.deleteAnalysisResultButton.setText(_translate("MainWindow", "Delete Analysis Result"))
        self.outputFieldViewButton.setText(_translate("MainWindow", "Output Field View"))
        self.terminalLabel.setText(_translate("MainWindow", "Terminal"))