import os, sys, r2pipe

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog

from Project import Project
from BinaryFile import BinaryFile
from Metadata import Metadata

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog

from pathlib import Path, PureWindowsPath

class ProjectTab(object):

    #def __init__(self):

    def setupProjectTab(self, tab):

        self.tab = tab
        self.ProjectDetailsContainer = QtWidgets.QGroupBox(self.tab)
        self.ProjectDetailsContainer.setGeometry(QtCore.QRect(240, 0, 981, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProjectDetailsContainer.sizePolicy().hasHeightForWidth())
        self.ProjectDetailsContainer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ProjectDetailsContainer.setFont(font)
        self.ProjectDetailsContainer.setObjectName("ProjectDetailsContainer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ProjectDetailsContainer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ProjectNameMainLayout = QtWidgets.QHBoxLayout()
        self.ProjectNameMainLayout.setObjectName("ProjectNameMainLayout")
        self.projectNameLabel = QtWidgets.QLabel(self.ProjectDetailsContainer)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.ProjectNameMainLayout.addWidget(self.projectNameLabel)
        spacerItem = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.ProjectNameMainLayout.addItem(spacerItem)
        self.projectNameField = QtWidgets.QLineEdit(self.ProjectDetailsContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.projectNameField.setFont(font)
        self.projectNameField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.projectNameField.setFrame(True)
        self.projectNameField.setReadOnly(True)
        self.projectNameField.setObjectName("projectNameField")
        self.ProjectNameMainLayout.addWidget(self.projectNameField)
        self.gridLayout_2.addLayout(self.ProjectNameMainLayout, 0, 0, 1, 1)
        self.ProjectDescriptionMainLayout = QtWidgets.QHBoxLayout()
        self.ProjectDescriptionMainLayout.setObjectName("ProjectDescriptionMainLayout")
        self.projectDescriptionLabel = QtWidgets.QLabel(self.ProjectDetailsContainer)
        self.projectDescriptionLabel.setObjectName("projectDescriptionLabel")
        self.ProjectDescriptionMainLayout.addWidget(self.projectDescriptionLabel)
        self.projectDescriptionField = QtWidgets.QTextEdit(self.ProjectDetailsContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.projectDescriptionField.setFont(font)
        self.projectDescriptionField.setReadOnly(True)
        self.projectDescriptionField.setObjectName("projectDescriptionField")
        self.ProjectDescriptionMainLayout.addWidget(self.projectDescriptionField)
        self.gridLayout_2.addLayout(self.ProjectDescriptionMainLayout, 1, 0, 1, 1)
        self.ProjectPathMainLayout = QtWidgets.QHBoxLayout()
        self.ProjectPathMainLayout.setObjectName("ProjectPathMainLayout")
        self.binaryFilePathLabel = QtWidgets.QLabel(self.ProjectDetailsContainer)
        self.binaryFilePathLabel.setObjectName("binaryFilePathLabel")
        self.ProjectPathMainLayout.addWidget(self.binaryFilePathLabel)
        spacerItem1 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.ProjectPathMainLayout.addItem(spacerItem1)
        self.binaryFilePathField = QtWidgets.QLineEdit(self.ProjectDetailsContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.binaryFilePathField.setFont(font)
        self.binaryFilePathField.setReadOnly(True)
        self.binaryFilePathField.setObjectName("binaryFilePathField")
        self.ProjectPathMainLayout.addWidget(self.binaryFilePathField)
        self.gridLayout_2.addLayout(self.ProjectPathMainLayout, 2, 0, 1, 1)
        self.ProjectPropertiesMainLayout = QtWidgets.QHBoxLayout()
        self.ProjectPropertiesMainLayout.setObjectName("ProjectPropertiesMainLayout")
        self.binaryFilePropertiesLabel = QtWidgets.QLabel(self.ProjectDetailsContainer)
        self.binaryFilePropertiesLabel.setObjectName("binaryFilePropertiesLabel")
        self.ProjectPropertiesMainLayout.addWidget(self.binaryFilePropertiesLabel)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.ProjectPropertiesMainLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.ProjectPropertiesMainLayout.addItem(spacerItem3)
        self.scrollArea = QtWidgets.QScrollArea(self.ProjectDetailsContainer)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 802, 221))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.fileProperties = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.fileProperties.setGeometry(QtCore.QRect(0, 0, 891, 451))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileProperties.setFont(font)
        self.fileProperties.setReadOnly(True)
        self.fileProperties.setObjectName("fileProperties")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setGeometry(QtCore.QRect(180, 0, 16, 541))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.ProjectPropertiesMainLayout.addWidget(self.scrollArea)
        self.gridLayout_2.addLayout(self.ProjectPropertiesMainLayout, 3, 0, 1, 1)
        self.ProjectSaveLayout = QtWidgets.QHBoxLayout()
        self.ProjectSaveLayout.setObjectName("ProjectSaveLayout")
        spacerItem4 = QtWidgets.QSpacerItem(4040, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.ProjectSaveLayout.addItem(spacerItem4)
        self.saveProjectButton = QtWidgets.QPushButton(self.ProjectDetailsContainer)
        self.saveProjectButton.setObjectName("saveProjectButton")
        self.ProjectSaveLayout.addWidget(self.saveProjectButton)
        self.gridLayout_2.addLayout(self.ProjectSaveLayout, 4, 0, 1, 1)
        self.ProjectViewContainer = QtWidgets.QGroupBox(self.tab)
        self.ProjectViewContainer.setGeometry(QtCore.QRect(0, 0, 231, 621))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ProjectViewContainer.setFont(font)
        self.ProjectViewContainer.setObjectName("ProjectViewContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ProjectViewContainer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProjectViewMainLayout = QtWidgets.QVBoxLayout()
        self.ProjectViewMainLayout.setObjectName("ProjectViewMainLayout")
        self.ProjectSearchLabel = QtWidgets.QLabel(self.ProjectViewContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ProjectSearchLabel.setFont(font)
        self.ProjectSearchLabel.setObjectName("ProjectSearchLabel")
        self.ProjectViewMainLayout.addWidget(self.ProjectSearchLabel)
        self.projectSearch = QtWidgets.QLineEdit(self.ProjectViewContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.projectSearch.setFont(font)
        self.projectSearch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.projectSearch.setObjectName("projectSearch")
        self.ProjectViewMainLayout.addWidget(self.projectSearch)
        self.ProjectMainLayout = QtWidgets.QVBoxLayout()
        self.ProjectMainLayout.setObjectName("ProjectMainLayout")
        self.ProjectsLabel = QtWidgets.QLabel(self.ProjectViewContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ProjectsLabel.setFont(font)
        self.ProjectsLabel.setObjectName("ProjectsLabel")
        self.ProjectMainLayout.addWidget(self.ProjectsLabel)
        self.projectList = QtWidgets.QListWidget(self.ProjectViewContainer)
        self.projectList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.projectList.setObjectName("projectList")
        self.ProjectMainLayout.addWidget(self.projectList)
        self.ProjectViewMainLayout.addLayout(self.ProjectMainLayout)
        self.verticalLayout_3.addLayout(self.ProjectViewMainLayout)
        self.ProjectButtonsLayout = QtWidgets.QHBoxLayout()
        self.ProjectButtonsLayout.setObjectName("ProjectButtonsLayout")
        self.projectNewButton = QtWidgets.QPushButton(self.ProjectViewContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.projectNewButton.setFont(font)
        self.projectNewButton.setObjectName("projectNewButton")
        self.ProjectButtonsLayout.addWidget(self.projectNewButton)
        self.projectDeleteButton = QtWidgets.QPushButton(self.ProjectViewContainer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.projectDeleteButton.setFont(font)
        self.projectDeleteButton.setObjectName("projectDeleteButton")
        self.ProjectButtonsLayout.addWidget(self.projectDeleteButton)
        self.verticalLayout_3.addLayout(self.ProjectButtonsLayout)

        return self.tab

    def retranslateProjectTab(self):

        _translate = QtCore.QCoreApplication.translate

        self.ProjectDetailsContainer.setTitle(_translate("MainWindow", "Detailed Project View"))
        self.projectNameLabel.setText(_translate("MainWindow", "Project Name"))
        self.projectDescriptionLabel.setText(_translate("MainWindow", "Project Description"))
        self.binaryFilePathLabel.setText(_translate("MainWindow", "Binary File Path"))
        self.binaryFilePropertiesLabel.setText(_translate("MainWindow", "Binary Properties"))
        self.saveProjectButton.setText(_translate("MainWindow", "     Save     "))
        self.ProjectViewContainer.setTitle(_translate("MainWindow", "Project View"))
        self.ProjectSearchLabel.setText(_translate("MainWindow", "Project Search"))
        self.ProjectsLabel.setText(_translate("MainWindow", "Projects"))
        self.projectNewButton.setText(_translate("MainWindow", " New "))
        self.projectDeleteButton.setText(_translate("MainWindow", " Delete "))